repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: no-commit-to-branch # both main and master are protected by default
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
        - --allow-missing-credentials
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
#    - id: terraform_tflint
#      args:
#        - --args=--module
#        - --args=--enable-rule=terraform_documented_variables
    - id: terraform_tfsec
    - id: terraform_validate
      args:
        - --args=-json
        - --args=-no-color
#    - id: terrascan
#      args:
#        - --args=--non-recursive
#    - id: infracost_breakdown

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.47.0
  hooks:
      - id: terraform_docs
        args: ["markdown", "table", "--output-file", "README.md", "./mymodule/path", "--config=.terraform-docs.yml"]
        #- --args=--config=.terraform-docs.yml
